env:
  global:
    
branches:
  only: 
    - master
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "10"
      install: true
      script: npm i && npm run tslint
    - stage: "Build"
      os: osx
      env: 
        - BuildiOS="12"
        - Xcode="10.0"
      osx_image: xcode10
      language: node_js 
      node_js: "10"
      jdk: oraclejdk8
      script:
        - tns build ios --bundle --env.aot --env.uglify
        - cd $IOS_PACKAGE_FOLDER && zip -r $IOS_PACKAGE $IOS_APP_NAME
        - "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $IOS_SAUCE_STORAGE --data-binary @$IOS_PACKAGE_FOLDER/$IOS_PACKAGE"
    - language: android
      env:
        - BuildAndroid="28"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 10
      script:
        - tns build android --bundle --env.aot --env.uglify --env.snapshot
        - "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $ANDROID_SAUCE_STORAGE --data-binary @$ANDROID_PACKAGE_FOLDER/app-debug.apk"    
    - os: linux
      env: 
        - iOS="11"
      language: node_js 
      node_js: "10"
      script: 
      #  - npm i -g appium@1.8.0
        - npm i
        - travis_wait travis_retry npm run e2e -- --runType sim.iPhone8 --sauceLab --appPath $IOS_PACKAGE
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - pip install six
    - echo no | npm install -g nativescript@latest --ignore-scripts
    - tns usage-reporting disable
    - tns error-reporting disable
